### ISSUE TITLE
[Todo]User Table 생성 및 "writer" -> "User"로 변경

### ISSUE THREAD

**Issue by uuuuj** [uuuuj/Express#15]
- [x] "writer" field 삭제
- [x] Posts table "writer" -> "userId"로 변경
- [x] Comments table "writer" -> "userId"로 변경
- [x] routes/post.js "writer" -> "userId"로 변경
- [x] routes/comments.js "writer" -> "userId"로 변경
