### ISSUE TITLE
[Todo] Userinfo 수정 및 1:1 관계 생성

### ISSUE THREAD

**Issue by uuuuj** [uuuuj/Express#18]
- [x] Userinfo Docs보고 따라 구현해보기
- [x] Users와 1:1 관계 생성하기
- [x] modify-user-info 수정
> - [ ] 'id' -> 'userinfoId' rename
> - [ ] 'UserId' remove and 'userId' add
> - [ ] 'name' addConstraint 
> - [ ] 'createdAt' addConstraint
> - [ ] 'updatedAt' addConstraint
